#!/bin/bash
# Deploy-parity check: does what is installed still match what this bundle ships?
#
# The repo is the source of truth; $HOME is what actually runs. They diverge the
# moment a merged change is not re-installed — and INSTALL.md §1's "never
# overwrite without asking" makes *skip* the honest answer on a re-install, so
# divergence is the default outcome rather than an unlucky one.
#
# This already happened: home/CLAUDE.md sat 7h ahead of ~/.claude/CLAUDE.md, so
# the live rules were missing an entire section describing two hooks that were
# installed and running, and still named skills EXCLUDED.md exists to record as
# removed. Nothing surfaced it, because a stale rules file loads, parses, and
# reads as authoritative exactly like a current one.
#
# Read-only by contract. It reports; it never repairs. Quietly fixing what it
# found would destroy the evidence of how far behind the machine had drifted —
# and the size of the gap is the finding, not just its existence.
#
#   ./tools/check-drift.sh              # checks $HOME
#   CHECK_ROOT=/tmp/x ./tools/check-drift.sh
#
# Exit codes are the contract:
#   0  every compared file matched
#   1  drift, a missing file, or an orphan
#   2  ABSTENTION — nothing of this bundle is installed at the root, so nothing
#      was compared. Deliberately distinct from 0: zero comparisons is not a
#      pass, and a fresh clone must not report parity it never checked.
set -u

BUNDLE="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="${CHECK_ROOT:-$HOME}"

FINDINGS=()
CHECKS_RUN=0
# Counts deployed FILES, never directories. An empty ~/.claude/hooks/ is not an
# install — treating the directory's existence as presence would turn the
# abstention below into a silent "1 target present, 4 things missing", which is
# the wrong answer for a machine that simply never ran INSTALL.md.
TARGETS_PRESENT=0

C_DIM=$'\033[38;2;85;85;85m'; C_GOLD=$'\033[38;2;240;192;64m'
C_RED=$'\033[38;2;220;80;80m'; C_OFF=$'\033[0m'

# Files whose content is this machine's, not the bundle's. The repo ships only
# rot-watch.example.json; the npm cache is generated by the siren. Flagging
# either would make a correct install permanently red, and a check that is
# always red is a check nobody reads.
is_machine_local() {
  case "$1" in
    rot-watch.json|.rot-npm-cache.json) return 0 ;;
    *) return 1 ;;
  esac
}

# The one expected difference. INSTALL.md §1 tells the installer to swap `~` for
# an absolute path when the import fails to resolve, so both forms are correct.
#
# This canonicalizes the import TARGET while leaving the rest of the line — and
# every other line — untouched. It is deliberately not a "skip line 6": an
# import rewritten to point somewhere else is the one edit that silently unloads
# every shared rule, and blanket-skipping the line would wave it straight
# through.
canonicalize() {
  sed 's|^@.*/\.config/ai-rules/global\.md$|@<SHARED-RULES>|' "$1"
}

compare_file() {
  local src="$1" dst="$2" label="$3"
  CHECKS_RUN=$((CHECKS_RUN + 1))
  if [ ! -f "$dst" ]; then
    FINDINGS+=("missing — $label is not installed at $dst")
    return
  fi
  TARGETS_PRESENT=$((TARGETS_PRESENT + 1))
  if ! diff -q <(canonicalize "$src") <(canonicalize "$dst") >/dev/null 2>&1; then
    FINDINGS+=("drift — $label differs from the bundle copy")
  fi
}

# Compares a directory both ways. The reverse direction is not symmetry for its
# own sake: a hook deleted from the bundle but still sitting in ~/.claude keeps
# firing every session, and only an orphan check can see it.
compare_dir() {
  local src="$1" dst="$2" label="$3" f rel

  while IFS= read -r f; do
    rel="${f#"$src"/}"
    is_machine_local "$(basename "$rel")" && continue
    CHECKS_RUN=$((CHECKS_RUN + 1))
    if [ ! -f "$dst/$rel" ]; then
      FINDINGS+=("missing — $label/$rel is not installed")
      continue
    fi
    TARGETS_PRESENT=$((TARGETS_PRESENT + 1))
    if ! diff -q "$f" "$dst/$rel" >/dev/null 2>&1; then
      FINDINGS+=("drift — $label/$rel differs from the bundle copy")
    fi
  done < <(find "$src" -type f 2>/dev/null | sort)

  [ -d "$dst" ] || return
  while IFS= read -r f; do
    rel="${f#"$dst"/}"
    is_machine_local "$(basename "$rel")" && continue
    CHECKS_RUN=$((CHECKS_RUN + 1))
    TARGETS_PRESENT=$((TARGETS_PRESENT + 1))
    [ -f "$src/$rel" ] || \
      FINDINGS+=("orphan — $label/$rel is installed but no longer in the bundle")
  done < <(find "$dst" -type f 2>/dev/null | sort)
}

compare_file "$BUNDLE/home/CLAUDE.md" \
             "$ROOT/.claude/CLAUDE.md" "CLAUDE.md"
compare_file "$BUNDLE/home/ai-rules/global.md" \
             "$ROOT/.config/ai-rules/global.md" "ai-rules/global.md"
compare_dir  "$BUNDLE/home/hooks" \
             "$ROOT/.claude/hooks" "hooks"
compare_dir  "$BUNDLE/home/skills/visual-decisions" \
             "$ROOT/.claude/skills/visual-decisions" "skills/visual-decisions"

# ---------------------------------------------------------------- abstention --
# Nothing of this bundle is here. Reporting "in sync" would be a claim about
# files that were never compared; reporting drift would be wrong too, since
# nothing was asked of this machine. Say what is true and use a third exit code.
if [ "$TARGETS_PRESENT" -eq 0 ]; then
  printf '%s⇄ DEPLOY DRIFT — nothing to check%s\n' "$C_GOLD" "$C_OFF"
  printf '  %sno part of this bundle is installed under %s%s\n' "$C_DIM" "$ROOT" "$C_OFF"
  printf '  %sthat is an abstention, not a pass — see INSTALL.md%s\n' "$C_DIM" "$C_OFF"
  exit 2
fi

if [ "${#FINDINGS[@]}" -eq 0 ]; then
  printf '%s⇄ deployed config in sync with the bundle%s %s(%d check(s))%s\n' \
    "$C_GOLD" "$C_OFF" "$C_DIM" "$CHECKS_RUN" "$C_OFF"
  exit 0
fi

printf '%s⇄ DEPLOY DRIFT — %d finding(s) across %d check(s)%s\n' \
  "$C_RED" "${#FINDINGS[@]}" "$CHECKS_RUN" "$C_OFF"
for f in "${FINDINGS[@]}"; do
  printf '  %s•%s %s\n' "$C_RED" "$C_OFF" "$f"
done
printf '\n  %sthe bundle at %s is the source of truth; re-copy, then re-apply%s\n' \
  "$C_DIM" "$BUNDLE" "$C_OFF"
printf '  %sthe absolutized @import from INSTALL.md §1 if you use it%s\n' \
  "$C_DIM" "$C_OFF"
exit 1
